newmetroapp/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// use controllers
use App\Http\Controllers\BookingController;
use App\Http\Controllers\TheatreController;
use App\Http\Controllers\CinemaController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\ConfigController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//
// Landing page route
// 
Route::get('/', function () {
    return view('welcome');
});

//
// Dashboard route
// 
Route::middleware(['auth'])->get('/dashboard', function () {
	return view('dashboard');
})->name('dashboard');

//
// Additional routes to controllers
//
Route::get('schedule/list/{cinema_id}/{movie_id}',  [ScheduleController::class, 'list']);
Route::get('theatre/id/{movie_id}/{cinema_id}',  [TheatreController::class, 'id']);
Route::get('config/maxseats',  [ConfigController::class,'maxseats']);
Route::get(
	'booking/remainingseats/{movie_id}/{cinema_id}/{show_time_id}/{theatre_id}/{max_number_seats}',	
	[BookingController::class,'remainingseats']
);

//
// Route action with auth
//
Route::post('booking', [ConfigController::class,'store'])->middleware('auth');
//
// Controller routes
//
Route::resources(['booking' => BookingController::class,]);
Route::resources(['theatre' => TheatreController::class,]);
Route::resources(['cinema' => CinemaController::class,]);
Route::resources(['movie' => MovieController::class,]);
Route::resources(['schedule' => ScheduleController::class,]);
Route::resources(['config' => ConfigController::class,]);

newmetroapp/app/Models/Theatre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Theatre extends Model
{
    use HasFactory;
}

newmetroapp/app/Http/Controllers/TheatreController.php
<?php

namespace App\Http\Controllers;

use App\Models\Theatre;
use App\Models\Movie;
use Illuminate\Http\Request;
use App\Repositories\Interfaces\TheatreRepositoryInterface;
use App\Repositories\Interfaces\MovieRepositoryInterface;

class TheatreController extends Controller
{
    private $theatreRepositoryInterface;

    /**
     * Constructor for controller
     *
     * @return void
     */
    public function __construct(
        TheatreRepositoryInterface $theatreRepositoryInterface,
        MovieRepositoryInterface $movieRepositoryInterface,
    )
    {
        $this->theatreRepositoryInterface = $theatreRepositoryInterface;
        $this->movieRepositoryInterface = $movieRepositoryInterface;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // get theatre list
        $theatres = $this->theatreRepositoryInterface->list();        

        return view('crud.theatre.list', ['theatres'=>$theatres]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Theatre  $theatre
     * @return \Illuminate\Http\Response
     */
    public function show(Theatre $theatre)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Theatre  $theatre
     * @return \Illuminate\Http\Response
     */
    public function edit(Theatre $theatre)
    {
        $info = $this->theatreRepositoryInterface->info($theatre->id);

        $movies = $this->movieRepositoryInterface->get();


        // load cancel a booking page
        return view('crud.theatre.edit', ['theatreInfo'=>$info, 'movies'=>$movies]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Theatre  $theatre
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Theatre $theatre)
    {
        // update theatre movie
        $status = $this->theatreRepositoryInterface->save(
            $theatre->id,
            $request->input('movie_id')
        );
        
        // redirect to theatre list
        return redirect('theatre')->with('status', $status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Theatre  $theatre
     * @return \Illuminate\Http\Response
     */
    public function destroy(Theatre $theatre)
    {
        //
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Theatre  $theatre
     * @return \Illuminate\Http\Response
     */
    public function id(int $movieId, $cinemaId)
    {
        // get theatre id selected
        $theatreId = $this->theatreRepositoryInterface->id(
            $movieId,
            $cinemaId
        );

        return ['theatre_id'=>$theatreId];
    }

}

newmetroapp/app/View/Components/CrudLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class CrudLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    // public function __construct()
    // {
    //     //
    // }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return view('layouts.crud');
    }
}

newmetroapp/app/View/Components/HeaderLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class HeaderLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    // public function __construct()
    // {
    //     //
    // }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return view('layouts.header');
    }
}

newmetroapp/resources/views/crud/theatre/edit.blade.php
<!-- header component -->
<x-header-layout>
</x-header-layout>

<x-crud-layout>
  <div class="container-fluid">
    
  
  <br><br>  
  <form action="/theatre/{{$theatreInfo->id}}" method="POST">
    @method('PUT')
    @csrf

		<div class="card text-center">
		  <div class="card-header">
		    Change movie for a theatre
		  </div>
		  <div class="card-body">	    
		    <p class="card-text font-weight-bold">Cinema</p>
		    <p class="card-text">{{$theatreInfo->name}}</p>
		    <br>
		    <p class="card-text font-weight-bold">Theatre</p>
		    <p class="card-text">{{$theatreInfo->theatre_name}}</p>
		    <br>
		    <p class="card-text font-weight-bold">Movie:</p>
		    <p class="card-text">
		    	@isset($movies)
			    	<select id='movie_id' name='movie_id'>
			    		@foreach($movies as $movie)
			    		<option value='{{$movie->id}}' 
			    			@if ($theatreInfo->movie_id == $movie->id)
			    				selected
			    			@endif
			    			>{{$movie->title}}</option>
			    		@endforeach
			    	</select>
		    	@endisset($movies)
		    </p>

		    <br>		    
		  </div>

		  <div class="card-footer text-muted">
		  	
		    	<button class="btn btn-primary">Confirm</button>
		    
		    	<a href="\theatre" class="btn btn-info">Return</a>
		  </div>
		</div>
	</form>   

  </div>
</x-crud-layout>

newmetroapp/resources/views/crud/theatre/list.blade.php
<!-- header component -->
<x-header-layout>
</x-header-layout>

<x-crud-layout>
  <div class="container-fluid">
    
    <br><br>
    Theatre admin
    <br><br>    
    Assign a theatre a new movie.
    <br><br>  

    @if(session('status'))
    <p class="card-text text-success">
      {{session('status')}}.
    </p>
    <br>
    @endif
    
    <table class="table table-sm">
      <thead>
        <tr>        
          <th scope="col">ID</th>
          <th scope="col">Cinema</th>
          <th scope="col">Movie</th>        
          <th scope="col">Theatre</th>
          <th scope="col">Updated</th>
          <th scope="col">Date created</th>        
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>

        @foreach ($theatres as $theatre) 
          <tr>          
            <th scope="row">{{$theatre->id}}</th>
            <td>{{$theatre->name}}</td>
            <td>{{$theatre->title}}</td>
            <td>{{$theatre->theatre_name}}</td>          
            <td>{{$theatre->updated_at}}</td>
            <td>{{$theatre->created_at}}</td>                    
            <td>            
                <a class='btn-sm btn-danger' role='button' href='theatre/{{$theatre->id}}/edit'>Change movie</a>
              
            </td>          
          </tr>        
        @endforeach      
      </tbody>    
    </table>

  </div>
</x-crud-layout>