newmetroapp/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// use controllers
use App\Http\Controllers\BookingController;
use App\Http\Controllers\TheatreController;
use App\Http\Controllers\CinemaController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\ConfigController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//
// Landing page route
// 
Route::get('/', function () {
    return view('welcome');
});

//
// Dashboard route
// 
Route::middleware(['auth'])->get('/dashboard', function () {
	return view('dashboard');
})->name('dashboard');

//
// Additional routes to controllers
//
Route::get('schedule/list/{cinema_id}/{movie_id}',  [ScheduleController::class, 'list']);
Route::get('theatre/id/{movie_id}/{cinema_id}',  [TheatreController::class, 'id']);
Route::get('config/maxseats',  [ConfigController::class,'maxseats']);
Route::get(
	'booking/remainingseats/{movie_id}/{cinema_id}/{show_time_id}/{theatre_id}/{max_number_seats}',	
	[BookingController::class,'remainingseats']
);

//
// Route action with auth
//
Route::post('booking', [ConfigController::class,'store'])->middleware('auth');
//
// Controller routes
//
Route::resources(['booking' => BookingController::class,]);
Route::resources(['theatre' => TheatreController::class,]);
Route::resources(['cinema' => CinemaController::class,]);
Route::resources(['movie' => MovieController::class,]);
Route::resources(['schedule' => ScheduleController::class,]);
Route::resources(['config' => ConfigController::class,]);

newmetroapp/app/Models/Booking.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use App\Models\Booking;
use App\Models\Config;
use App\Models\CinemaSchedule;

class Booking extends Model
{
    use HasFactory;
}

newmetroapp/app/Http/Controllers/BookingController.php
<?php

namespace App\Http\Controllers;

use App\Models\Booking;
use App\Models\Cinema;
use App\Models\Movie;
use App\Models\Schedule;
use App\Models\Config;
use App\Models\User;
use App\Models\Theatre;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use App\Repositories\Interfaces\CinemaRepositoryInterface;
use App\Repositories\Interfaces\BookingRepositoryInterface;
use App\Repositories\Interfaces\MovieRepositoryInterface;
use App\Repositories\Interfaces\ScheduleRepositoryInterface;
use App\Repositories\Interfaces\TheatreRepositoryInterface;
use App\Repositories\Interfaces\ConfigRepositoryInterface;

class BookingController extends Controller
{

    private $cinemaRepositoryInterface;
    private $bookingRepositoryInterface;
    private $movieRepositoryInterface;
    private $scheduleRepositoryInterface;
    private $theatreRepositoryInterface;
    private $configRepositoryInterface;

    /**
     * Constructor for controller
     *
     * @return void
     */
    public function __construct(
        CinemaRepositoryInterface $cinemaRepositoryInterface,
        BookingRepositoryInterface $bookingRepositoryInterface,
        MovieRepositoryInterface $movieRepositoryInterface,
        ScheduleRepositoryInterface $scheduleRepositoryInterface,
        TheatreRepositoryInterface $theatreRepositoryInterface,
        ConfigRepositoryInterface $configRepositoryInterface,
    )
    {
        // set properties
        $this->cinemaRepositoryInterface = $cinemaRepositoryInterface;
        $this->bookingRepositoryInterface = $bookingRepositoryInterface;
        $this->movieRepositoryInterface = $movieRepositoryInterface;
        $this->scheduleRepositoryInterface = $scheduleRepositoryInterface;
        $this->theatreRepositoryInterface = $theatreRepositoryInterface;
        $this->configRepositoryInterface = $configRepositoryInterface;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        // get booking list
        $bookings = $this->bookingRepositoryInterface->list(Auth::user());        

        return view('booking.list', ['bookings'=>$bookings]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // fetch cinemas
        $cinemas = $this->cinemaRepositoryInterface->get();
        
        // return view
        return view('booking.create', ['cinemas'=>$cinemas]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {           
        // redirect user if not logged in.
        // having issues with middleware
        if (!Auth::check()) 
            return redirect('/login');

        // get the show date and time
        $showDateAndTime = $this->scheduleRepositoryInterface->showDateTime(
            $request->input('show_time_id')
        );

        // get the ticket price
        $ticketPrice = $this->configRepositoryInterface->value('ticket_price');

        // set attributes of booking in assoc array
        $attributes = [
            "cinema_id"=>$request->input('cinema_id'),
            "movie_id"=>$request->input('movie_id'),
            "show_time_id"=>$request->input('show_time_id'),
            "theatre_id"=>$request->input('theatre_id'),
            "seats"=>$request->input('seats'),
            "ticket_price"=>$ticketPrice,
            "show_date_and_time"=>$showDateAndTime
        ];

        // place booking
        $status = $this->bookingRepositoryInterface->save($attributes, Auth::user());

        
        // redirect user to dashboard to view order
        if ($status["is_saved"]) {

            // redirect user to the booking dashboard
            return redirect('booking')->with('status', $status);            
        }

        // show the save error if any
        return view('booking.create', ['status' => $status]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function show(Booking $booking)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function edit(Booking $booking)
    {   
        // check if movie can be cancelled
        $cancelMovie = $this->bookingRepositoryInterface->isCancellationAllowed(
            $booking->id, Auth::user()
        );

        // get booking info for the logged in user
        $bookingInfo = $this->bookingRepositoryInterface->info($booking->id, Auth::user());

        // load cancel a booking page
        return view('booking.edit', ['bookingInfo'=>$bookingInfo,'cancelMovie'=>$cancelMovie]);       
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Booking $booking)
    {
        

        // cancel a booking
        $result = $this->bookingRepositoryInterface->cancel(
            $booking->id,
            Auth::user(),
            $booking
        );
        
        // redirect to booking list if booking saved successfully.
        if ($result['status'])
            return redirect('booking')->with('result', $result);        
        

        // show error message to user
        return view('booking.edit', ['bookingInfo'=>$booking,'result'=>$result]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function destroy(Booking $booking)
    {
        //
    }

    /**
     * Get remaining seat count
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function remainingseats($movieId, $cinemaId, $showTimeId, $theatreId, $maxNumberSeats)
    {        
        $remainingSeats =$this->bookingRepositoryInterface->remainingSeatCount(
            $movieId, $cinemaId, $showTimeId, $theatreId, $maxNumberSeats
        );

        return ['remaining_seat_count' => $remainingSeats];
    }
    
}

newmetroapp/app/View/Components/DashboardLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class DashboardLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    // public function __construct()
    // {
    //     //
    // }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return view('layouts.dashboard');
    }
}

newmetroapp/app/View/Components/HeaderLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class HeaderLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    // public function __construct()
    // {
    //     //
    // }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return view('layouts.header');
    }
}

newmetroapp/resources/views/booking/edit.blade.php
<!-- header component -->
<x-header-layout>
</x-header-layout>

<x-dashboard-layout>

<div class="container-fluid">
  
  <br><br>  
  <form action="/booking/{{$bookingInfo->id}}" method="POST">
    @method('PUT')
    @csrf

		<div class="card text-center">
		  <div class="card-header">
		    Cancel booking
		  </div>
		  <div class="card-body">	    
		    <p class="card-text font-weight-bold">Title</p>
		    <p class="card-text">{{$bookingInfo->title}}</p>
		    <br>
		    <p class="card-text font-weight-bold">Movie rating:</p>
		    <p class="card-text">{{$bookingInfo->rating}}</p>
		    <br>
		    <p class="card-text font-weight-bold">Number of seats booked</p>
		    <p class="card-text">{{$bookingInfo->number_of_seats}}</p>
		    <br>
		    <p class="card-text font-weight-bold">Total cost</p>
		    <p class="card-text">{{$bookingInfo->total_cost}}</p>
		    <br>

		    <p class="card-text font-weight-bold">Show time</p>
		    <p class="card-text">
		    	{{$bookingInfo->show_date}}	    	
		    </p>
		    <br>
		    @isset($result)		    
		    	@if (!$result["status"])
		    		<p class="card-text text-danger">{{$result["message"]}}</p>
		    	@endif
		    @endisset		    
		  </div>
		  <div class="card-footer text-muted">

		  	
		    <button class="btn btn-primary">Confirm</button>
		    
		    <a href="\booking" class="btn btn-info">Return</a>
		  </div>
		</div>
	</form>
</div>

</x-dashboard-layout>

newmetroapp/resources/views/booking/list.blade.php
<!-- header component -->
<x-header-layout>
</x-header-layout>

<x-dashboard-layout>

<div class="container-fluid">
  
  <br><br>
  Your bookings
  <br><br>  

  @if(session('result'))
    @if(session('result')['status'])
      <p class="card-text text-success">
        {{session('result')['message']}}.
      </p>
      <br>
    @endif
  @endif

  @if(session('result'))
    @if(!session('result')['status'])
      <p class="card-text text-error">
        {{session('result')['message']}}.
      </p>
      <br>
    @endif
  @endif
  
  <table class="table table-sm">
    <thead>
      <tr>        
        <th scope="col">Reference</th>
        <th scope="col">Cinema</th>
        <th scope="col">Movie</th>
        <th scope="col">Show Time</th>
        <th scope="col">Seats</th>
        <th scope="col">Total cost</th>
        <th scope="col">Date created</th>
        <th scope="col">Status</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>

      @foreach ($bookings as $booking) 
        <tr>          
          <th scope="row">{{$booking->reference}}</th>
          <td>{{$booking->name}} ({{$booking->theatre_name}})</td>
          <td>{{$booking->title}}</td>
          <td>{{$booking->show_date}}</td>
          <td>{{$booking->number_of_seats}}</td>
          <td>R{{$booking->total_cost}}</td>
          <td>{{$booking->created_at}}</td>
          <td>
              @if ($booking->status=='booked')
                <span class="badge badge-success">{{$booking->status}}</span>
              @else 
                <span class="badge badge-secondary">{{$booking->status}}</span>
              @endif
          </td>          
          <td>
            @if ($booking->status=='booked')
              <a class='btn-sm btn-danger' role='button' href='booking/{{$booking->id}}/edit'>Cancel</a>
            @endif
          </td>
          <td></td>
        </tr>        
      @endforeach      
    </tbody>    
  </table>

</div>

</x-dashboard-layout>